07 lection5 01 checkbox
js-tasks-ru/htmlcss-20220519_mraleksej pull request #12
Opened 2022-06-14 20:06 UTC by MrAleksej

Добавлено решение по верстке Чекбокса

2022-06-14 20:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-14 20:39 UTC, GSemikozov requested changes

2022-06-14 20:39 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    background: #DDE2E5;
и не забываем в нужно месте указать pointer-events: none

2022-06-15 08:09 UTC, MrAleksej commented on 07-lection5/01-checkbox/checkbox.css
> +    background: #DDE2E5;
исправлено)

2022-06-17 20:39 UTC, GSemikozov approved these changes

2022-06-17 20:39 UTC, merged