add 04-lection2-01-histogram solution
js-tasks-ru/htmlcss-20220519_mraleksej pull request #7
Opened 2022-05-30 10:46 UTC by MrAleksej

Добавлено решение по верстке гистограммы (лекция 2, задача 1)

2022-05-30 10:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-30 15:19 UTC, GSemikozov requested changes

2022-05-30 15:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 24px;
39 по дизайну

2022-05-30 15:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 2px;
1px

2022-05-30 15:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
flex-basis

2022-05-30 15:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
+ flex-grow: 1

2022-05-31 10:13 UTC, MrAleksej commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 24px;
исправлено

2022-05-31 10:20 UTC, MrAleksej commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
исправлено)
спасибо, наконец понял на практике, для чего он нужен)

2022-06-10 18:53 UTC, GSemikozov approved these changes

2022-06-10 18:53 UTC, merged