add 05-lection3-01-tooltip solution
js-tasks-ru/htmlcss-20220519_mraleksej pull request #9
Opened 2022-06-05 10:47 UTC by MrAleksej

Добавлено решение по верстке тултипа

2022-06-05 10:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-05 10:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-05 18:11 UTC, GSemikozov requested changes

2022-06-05 18:11 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body{
вспомогательные /глобальные стили ни в коем случае не нужно размещать внутри стилей компонента

2022-06-05 18:11 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    position: absolute;
иконку не нужно никак позиционировать, у нее стандартный position: static

2022-06-05 20:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-05 20:24 UTC, MrAleksej commented on 05-lection3/01-tooltip/tooltip.css
> +body{
понял! исправлено)

2022-06-05 20:24 UTC, MrAleksej commented on 05-lection3/01-tooltip/tooltip.css
> +    position: absolute;
исправлено)

2022-06-10 18:55 UTC, GSemikozov requested changes

2022-06-10 18:55 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.page{
как писал ранее - вспомогательные стили не относящиеся к стилям блока выносим (можно добавить например в тег style на странице с решением)

2022-06-13 11:07 UTC, MrAleksej commented on 05-lection3/01-tooltip/tooltip.css
> +.page{
понял) сделано)

2022-06-13 20:56 UTC, MrAleksej commented on 05-lection3/01-tooltip/tooltip.css
> +    top:100px;
исправлено) добавил тег в body

2022-06-14 20:13 UTC, GSemikozov approved these changes

2022-06-14 20:13 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-06-14 20:15 UTC, GSemikozov approved these changes

2022-06-14 20:15 UTC, merged